// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Core.EntityFramework;

#nullable disable

namespace TodoApp.Core.Migrations
{
    [DbContext(typeof(UserTasksDbContext))]
    partial class UserTasksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TodoApp.Core.DataModels.TaskList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskLists");
                });

            modelBuilder.Entity("TodoApp.Core.DataModels.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsImportant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RemindUserUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("TodoApp.Core.EntityFramework.UserTaskListsJoinedTable", b =>
                {
                    b.Property<Guid>("UserTaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskListId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserTaskId", "TaskListId");

                    b.HasIndex("TaskListId");

                    b.ToTable("UserTaskLists");
                });

            modelBuilder.Entity("TodoApp.Core.DataModels.UserTask", b =>
                {
                    b.OwnsMany("TodoApp.Core.DataModels.Step", "Steps", b1 =>
                        {
                            b1.Property<Guid>("UserTaskId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsCompleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false);

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("UserTaskId", "Id");

                            b1.ToTable("Step");

                            b1.WithOwner()
                                .HasForeignKey("UserTaskId");
                        });

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("TodoApp.Core.EntityFramework.UserTaskListsJoinedTable", b =>
                {
                    b.HasOne("TodoApp.Core.DataModels.TaskList", "TaskList")
                        .WithMany("UserTaskLists")
                        .HasForeignKey("TaskListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoApp.Core.DataModels.UserTask", "UserTask")
                        .WithMany("UserTaskLists")
                        .HasForeignKey("UserTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskList");

                    b.Navigation("UserTask");
                });

            modelBuilder.Entity("TodoApp.Core.DataModels.TaskList", b =>
                {
                    b.Navigation("UserTaskLists");
                });

            modelBuilder.Entity("TodoApp.Core.DataModels.UserTask", b =>
                {
                    b.Navigation("UserTaskLists");
                });
#pragma warning restore 612, 618
        }
    }
}
